/**
 * Single re-export point for every Lucide icon the studio uses.
 *
 * Two reasons to funnel through this file:
 *   1. One place to swap icon-pack vendor if Lucide ever changes its API or
 *      we want to subset the icon bundle.
 *   2. Lets every feature do
 *        import { Bold, Italic, AlignLeft } from "@theme/icons";
 *      instead of pulling the whole `lucide-react` namespace on each call
 *      site (matches the monolith's flat import style).
 */
export {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  AlignVerticalJustifyStart,
  ArrowDown,
  ArrowUp,
  BarChart2,
  Blend,
  Bold,
  BoxSelect,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Clock,
  Columns3,
  Copy,
  Crosshair,
  Database,
  Eye,
  EyeOff,
  FileDigit,
  FileImage,
  FileJson,
  Filter,
  Frame,
  GripHorizontal,
  GripVertical,
  Hash,
  ImageIcon,
  Italic,
  Layers,
  LayoutGrid,
  LayoutTemplate,
  LineChart,
  Link,
  List,
  Lock,
  Maximize2,
  Minus,
  MoreVertical,
  Move,
  Palette,
  PanelBottom,
  PanelTop,
  PieChart,
  Pilcrow,
  Pin,
  Plus,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Ruler,
  Save,
  Search,
  SeparatorHorizontal,
  Settings2,
  Sliders,
  SlidersHorizontal,
  Spline,
  Square,
  Table2,
  TextCursor,
  Trash2,
  TrendingUp,
  Type,
  Unlock,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
