/**
 * Single re-export point for every Lucide icon the studio uses.
 *
 * Two reasons to funnel through this file:
 *   1. One place to swap icon-pack vendor if Lucide ever changes its API or
 *      we want to subset the icon bundle.
 *   2. Lets every feature do
 *        import { Bold, Italic, AlignLeft } from "@theme/icons";
 *      instead of pulling the whole `lucide-react` namespace on each call
 *      site (matches the monolith's flat import style).
 */
export {
  Type,
  ImageIcon,
  Minus,
  Clock,
  GripVertical,
  X,
  FileJson,
  ZoomIn,
  ZoomOut,
  LayoutTemplate,
  Table2,
  PanelTop,
  PanelBottom,
  Settings2,
  Plus,
  Trash2,
  RotateCw,
  Move,
  Maximize2,
  Bold,
  Italic,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Palette,
  Layers,
  SeparatorHorizontal,
  FileDigit,
  Copy,
  Check,
  ChevronRight,
  ChevronLeft,
  Ruler,
  Columns3,
  SlidersHorizontal,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  ArrowUp,
  ArrowDown,
  Sliders,
  RotateCcw,
  RefreshCw,
  Filter,
  Database,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  Crosshair,
  LayoutGrid,
  TextCursor,
  Spline,
  Square,
  Frame,
  BoxSelect,
  Blend,
  BarChart2,
  PieChart,
  LineChart,
  FileImage,
  AlignVerticalJustifyStart,
  List,
  MoreVertical,
  Pin,
  GripHorizontal,
  TrendingUp,
  Pilcrow,
  Link,
  Hash,
  Search,
  Save,
  Upload,
} from "lucide-react";
