import { StyleSheet } from "@react-pdf/renderer";

/**
 * Native Vector PDF Stylesheet for @react-pdf/renderer
 */
export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 48,
    paddingHorizontal: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#0F172A",
    backgroundColor: "#FFFFFF",
  },
  coverPage: {
    padding: 40,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    backgroundColor: "#FAFAFA",
    borderWidth: 2,
    borderColor: "#E2E8F0",
    borderRadius: 8,
  },
  coverLogo: {
    width: 56,
    height: 56,
    marginBottom: 20,
  },
  coverSub: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#2563EB",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 16,
  },
  coverTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#0F172A",
    textAlign: "center",
    marginBottom: 16,
  },
  coverDate: {
    fontSize: 11,
    color: "#64748B",
    marginBottom: 28,
  },
  coverBadge: {
    paddingVertical: 5,
    paddingHorizontal: 16,
    backgroundColor: "#2563EB",
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "bold",
    borderRadius: 14,
  },
  headerBadge: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#CBD5E1",
    paddingBottom: 8,
    marginBottom: 16,
  },
  headerPath: {
    fontSize: 9,
    fontFamily: "Courier",
    color: "#2563EB",
    fontWeight: "bold",
  },
  headerMeta: {
    fontSize: 8,
    fontFamily: "Courier",
    color: "#64748B",
  },
  sectionTitle: {
    fontSize: 9,
    fontFamily: "Courier",
    fontWeight: "bold",
    color: "#2563EB",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  h1: {
    fontSize: 18,
    fontFamily: "Helvetica",
    fontWeight: "bold",
    color: "#0F172A",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    paddingBottom: 4,
    marginTop: 12,
    marginBottom: 10,
  },
  h2: {
    fontSize: 14,
    fontFamily: "Helvetica",
    fontWeight: "bold",
    color: "#0F172A",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    paddingBottom: 4,
    marginTop: 14,
    marginBottom: 8,
  },
  h3: {
    fontSize: 12,
    fontFamily: "Helvetica",
    fontWeight: "bold",
    color: "#1E293B",
    marginTop: 10,
    marginBottom: 6,
  },
  paragraph: {
    fontSize: 9.5,
    lineHeight: 1.5,
    color: "#334155",
    marginBottom: 8,
  },
  bold: {
    fontFamily: "Helvetica",
    fontWeight: "bold",
    color: "#0F172A",
  },
  codeBadge: {
    fontFamily: "Courier",
    fontSize: 8.5,
    color: "#2563EB",
    backgroundColor: "#F1F5F9",
    borderWidth: 0.5,
    borderColor: "#CBD5E1",
    borderRadius: 3,
    paddingVertical: 1,
    paddingHorizontal: 4,
  },
  listRow: {
    display: "flex",
    flexDirection: "row",
    marginBottom: 4,
    paddingLeft: 10,
  },
  bulletDot: {
    width: 12,
    fontSize: 10,
    color: "#2563EB",
  },
  listText: {
    flex: 1,
    fontSize: 9.5,
    lineHeight: 1.5,
    color: "#334155",
  },
  blockquote: {
    borderLeftWidth: 3,
    borderLeftColor: "#2563EB",
    backgroundColor: "#F8FAFC",
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginVertical: 8,
    borderRadius: 3,
  },
  blockquoteText: {
    fontSize: 9,
    fontFamily: "Helvetica-Oblique",
    color: "#475569",
    lineHeight: 1.4,
  },
  table: {
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 4,
  },
  tableRow: {
    display: "flex",
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    paddingVertical: 5,
    paddingHorizontal: 6,
  },
  tableHeaderRow: {
    backgroundColor: "#F8FAFC",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  tableCellHeader: {
    fontSize: 8.5,
    fontFamily: "Helvetica",
    fontWeight: "bold",
    color: "#0F172A",
    flex: 1,
  },
  tableCell: {
    fontSize: 8.5,
    color: "#334155",
    flex: 1,
  },
  codeBlock: {
    backgroundColor: "#0F172A",
    borderRadius: 6,
    padding: 8,
    marginVertical: 8,
  },
  codeBlockText: {
    fontFamily: "Courier",
    fontSize: 8,
    color: "#E2E8F0",
    lineHeight: 1.3,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
    paddingTop: 8,
    fontSize: 8,
    fontFamily: "Courier",
    color: "#94A3B8",
  },
});
